export default {
  NODE_ENV: process.env.NODE_ENV,
  HTTPBASEURL: process.env.HTTPBASEURL,
  HTTPCMSURL: process.env.HTTPCMSURL, // 请求CMS的接口
  HTTPOPENAPIURL: process.env.HTTPOPENAPIURL, // 请求OPENAPI的接口
  HTTPHEADER_APPID: process.env.HTTPHEADER_APPID,
  HTTPHEADER_APPVERSION: process.env.HTTPHEADER_APPVERSION,
  HTTPHEADER_APPSIGN: process.env.HTTPHEADER_APPSIGN,
  MOCK_USERINFO: process.env.MOCK_USERINFO
};
